#!/usr/bin/env bash
# Bash script configures Nginx to run and listen to port 80 in Ubuntu container.
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
